export const enum TestCode {
  STD = 'STD',
  PRO = 'PRO',
  VIS = 'VIS',
  VES = 'VES',
  STG_0 = 'STG_0',
  STG_1 = 'STG_1',
  STG_2 = 'STG_2',
  STG_3 = 'STG_3',
  STG_4 = 'STG_4',
  BAL_0 = 'BAL_0',
  BAL_1 = 'BAL_1',
  BAL_2 = 'BAL_2',
  BAL_3 = 'BAL_3',
  BAL_4 = 'BAL_4',
  STAB_0 = 'STAB_0',
  STAB_1 = 'STAB_1',
  STAB_2 = 'STAB_2',
  STAB_3 = 'STAB_3',
  STAB_4 = 'STAB_4',
  CONC_0 = 'CONC_0',
  CONC_1 = 'CONC_1',
  CONC_2 = 'CONC_2',
  CONC_3 = 'CONC_3',
  CONC_4 = 'CONC_4'
}
